# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='songDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=500)),
                ('name_of_song', models.CharField(max_length=100)),
                ('hash_code', models.CharField(max_length=34)),
                ('score', models.IntegerField()),
                ('email_id', models.EmailField(max_length=254)),
                ('karaoke_created', models.BooleanField(default=False)),
            ],
        ),
    ]
